### ISSUE TITLE
Error starting start.rb

### ISSUE THREAD

**Issue by AlexisTM** [acsl-mipt/multiple-sitl#1]
Starting the script from **Ubuntu 14.04** throw an error. 

```
$ ruby start.rb -h
./start.rb:13:in `<main>': undefined local variable or method `__dir__' for main:Object (NameError)
```

**Comment by korotkoves** [comment]
1) Project tested on Ubuntu 16.04 (Xenial)
2)  Update Ruby version to 2.0 or higher

**Comment by AlexisTM** [comment]
Thanks for your fast reply!

Ruby 2.0 solved the problem.

**Comment by AlexisTM** [comment]
This is working like a charm, thanks a lot!

**Comment by paan2097** [comment]
I'm struggling to use start.rb as well, here is what i am getting:

./start.rb:167:in `spawn': No such file or directory - roslaunch (Errno::ENOENT)
	from ./start.rb:167:in `block (2 levels) in <main>'
	from /usr/lib/ruby/2.3.0/fileutils.rb:128:in `chdir'
	from /usr/lib/ruby/2.3.0/fileutils.rb:128:in `cd'
	from ./start.rb:163:in `block in <main>'
	from ./start.rb:96:in `times'
	from ./start.rb:96:in `<main>'

Can you please help please? @korotkoves

**Comment by paan2097** [comment]
I'm using ubuntu 16.04.1 and ruby 2.3.1p112

**Comment by korotkoves** [comment]
Install ROS + mavros (see README)

**Comment by AlexisTM** [comment]
If already installed, do not forget to source it :

```
source /opt/ros/...indigo or kinetic.../setup.bash
```

**Comment by paan2097** [comment]
Hey guys, one step further ahead and I'm trying to launch two planes. Here's where I am at:
pat@pat-VirtualBox:~/multiple-sitl$ ./start.rb -m plane -n 2
pat@pat-VirtualBox:~/multiple-sitl$ Gazebo multi-robot simulator, version 7.6.0
Copyright (C) 2012 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

[Msg] Waiting for master.
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 127.0.0.1
Gazebo multi-robot simulator, version 7.6.0
Copyright (C) 2012 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

[Msg] Waiting for master.
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 127.0.0.1
Error [parser.cc:293] Error parsing XML in file [/home/pat/multiple-sitl/default.world]: Error document empty.
[Err] [Server.cc:391] Unable to read sdf file[default.world]
[Wrn] [Server.cc:335] Falling back on worlds/empty.world
[Wrn] [Event.cc:87] Warning: Deleteing a connection right after creation. Make sure to save the ConnectionPtr from a Connect call

**Comment by paan2097** [comment]
Hey guys, thanks a lot for the help I have the multiple SITL running. I need help on two issues: running simulator with multiple planes, what changes do I have to make? Also, when I connect via dronekit script, I get this error:

pat@pat-VirtualBox:~/Firmware/integrationtests/python_src/px4_it/dronekit$ python MissionCheck.py 
Connecting
 Type: 2
 Armed?: False
 System status: STANDBY
 GPS: GPSInfo:fix=3,num_sat=10
 Alt: -0.029
Waiting for home position...
Waiting for home position...
 Uploaded mission with 4 items
current mission sequence: 0
>>> Executing mission
>>> Takeoff to 10.0 meters above home
>>> Exception in message handler for HEARTBEAT
>>> mode 67371008 not available on mavlink definition
Waiting for vehicle to arm...
>>> ARMED by arm/disarm component command
>>> Takeoff detected
Waiting for vehicle to arm...
>>> Exception in message handler for HEARTBEAT
>>> mode 67371008 not available on mavlink definition
Waiting for vehicle to arm...
>>> Exception in message handler for HEARTBEAT
>>> mode 67371008 not available on mavlink definition


I've posted this one every forum, px4, emlid....please help!

**Comment by korotkoves** [comment]
Multiple planes seems to be easy to add, may be later, in free time.
I'm using mavros, so can't help about dronekit, errors may be due to mavlink versions incompatibilities.

**Comment by paan2097** [comment]
@korotkoves Solved that mode problem, upgraded libraries and got new dronekit/pymavlink. I need to run multiple planes, I would like to use this repo for planes, what changes would I have to make?
I tried to do multiple planes in SITL using PX4 using this file:
https://github.com/PX4/Firmware/blob/master/Tools/sitl_multiple_run.sh
Two instances of PX4 are started but reach this line:
Please start the flight simulator to proceed..
I want to connect to these two px4 sitl instances using dronekit scripts....but it is telling me I need to start a gazebo...How do I create either two gazebos, or even better one gazebo with both planes?
Thanks!
