### ISSUE TITLE
Official PX4 support

### ISSUE THREAD

**Issue by LorenzMeier** [acsl-mipt/multiple-sitl#3]
Hi,

This looks rather useful and like something a lot more PX4 users could be using. Would you be interested to contribute this to the upstream PX4 project?

@dagar FYI

Thanks!

-Lorenz

**Comment by korotkoves** [comment]
Yes, I will be glad if this work helps on PX4 project.

**Comment by korotkoves** [comment]
Closing issue, no interest from PX4.
