### ISSUE TITLE
Cmake error....

### ISSUE THREAD

**Issue by CrazyDominic** [acsl-mipt/multiple-sitl#4]
If I command "./prepare.sh", terminal shows error that is error: ‘class gazebo::rendering::Scene’ has no member named ‘GetSimTime’
   common::Time currentTime = scene_->GetSimTime();

Why has this error happened? Could explain ?

**Comment by korotkoves** [comment]
May be you installed Gazebo 8 (this project works with Gazebo 7).
Uninstall all gazebo files and try ./install/all.sh to install dependencies and build the project.
