### ISSUE TITLE
Document the usage on PX4 devguide

### ISSUE THREAD

**Issue by TSC21** [acsl-mipt/multiple-sitl#5]
Considering the fact this could be useful upstream for multiple PX4 users and developers, and considering #3, I consider this should be documented on our devguide, specially referring it's existance and how to use it. @hamishwillee maybe we can create an issue on the devguide repo so this can be started?
@korotkoves are you available to aid on documenting the usage of this repo on PX4 Devguide? I know you already have a description on your README, but would be extremely useful to have this synced with our SITL and Gazebo docs.
@LorenzMeier FYI.

**Comment by hamishwillee** [comment]
@TSC21 @korotkoves This is so cool! 
We already have an issue in place for this:  https://github.com/PX4/Devguide/issues/384 :-)

The _easiest_ way to do this is to create a separate topic *Multi Vehicle Simulation (Gazebo)* alongside our [current multi-vehicle topic](https://dev.px4.io/en/simulation/multi-vehicle-simulation.html) (renamed to *Multi Vehicle Simulation (ROS/Gazebo)*). Ideally the docs should explain not just what to do, but briefly outline how it works, and how it can be extended (ie what if you wanted to use something other than iris). 

However if the new approach can be used with ROS too (?), and is sufficiently better/more flexible, then might be better to replace the old doc/approach with this new method and add a section at the end on working with ROS too. Thoughts?

For my information, how integrated is this with PX4 repos? Ie ideally instructions should reference PX4 or Dronecode Github org repos, not acsl-mipt. I.e. should https://github.com/acsl-mipt/multiple-sitl/issues/3 be closed by https://github.com/PX4/sitl_gazebo/pull/199 ?

@korotkoves I can help with editing, testing and advice. Let me know if you need anything else :-)

**Comment by TSC21** [comment]
> @TSC21 @korotkoves This is so cool!
We already have an issue in place for this: PX4/Devguide#384 :-)

Oh I totally missed that! Thanks for the heads up!

> The easiest way to do this is to create a separate topic Multi Vehicle Simulation (Gazebo) alongside our current multi-vehicle topic (renamed to Multi Vehicle Simulation (ROS/Gazebo)). Ideally the docs should explain not just what to do, but briefly outline how it works, and how it can be extended (ie what if you wanted to use something other than iris).

I totally agree.

> However if the new approach can be used with ROS too (?), and is sufficiently better/more flexible, then might be better to replace the old doc/approach with this new method and add a section at the end on working with ROS too. Thoughts?

This approach, from my understand, can be used with and without ROS. We just have to properly document on how/why/what do those approaches do. If it is a replacement? I don't actually consider it a replacement yet. I do think it needs to be more refined and simplified in terms of how this actually integrates and tights with our PX4 repos. It seems to currently wrap the repos and generate new files from those, but I think we can actually integrate this into PX4 in a more specific and simpler fashion.

> For my information, how integrated is this with PX4 repos? Ie ideally instructions should reference PX4 or Dronecode Github org repos, not acsl-mipt. I.e. should #3 be closed by PX4/sitl_gazebo#199 ?

It's not actually integrated but rather wraps up the repos and gets the files and data it needs from them. This is an approach created by acsl-mipt and by the hard work of @korotkoves, but in the end, if we want ti reference it, it would have to be as an external solution to PX4 as it is right now. The way the scripts are built does not allow an easy integration on our workspace, so I guess for an acceptable integration, some of what is in this repo should be rewritten in order to be integrated as a script or as a git submodule on our PX4 Firmware `Tools`. PX4/sitl_gazebo#199 does not close #3. It rather guarantees that `multiple_sitl` works.

**Comment by hamishwillee** [comment]
@TSC21 Thanks for the clarifications. In that case separate doc makes sense. Ideally this should have a section on how you use this with ROS too, but that could come later if it is too hard (I guess a question for @korotkoves ) 

I do hope it moves towards a tighter integration, but this is a great start, and well worth documenting now.  The docs should probably start with a note explaining the current status and a link to #3 for tracking (probably just a sentence in a note).

**Comment by korotkoves** [comment]
@TSC21, @hamishwillee please review modified README in https://github.com/acsl-mipt/multiple-sitl/tree/for-px4-pr for errors. I think that writing proper chapter for Devguide is for more native English speaker than me :) I ready to answer to any questions if needed.

**Comment by korotkoves** [comment]
Closing issue, no interest from PX4.

**Comment by hamishwillee** [comment]
@korotkoves Not so much "no interest" as "forgot about this due to millions of outstanding issues". I think we'd still love this. I'll see if I can get someone to retest it and then get it in. 
No need to reopen - tracking through https://github.com/PX4/Devguide/issues/384
