### ISSUE TITLE
Vehicle don't connect to QGroundControl

### ISSUE THREAD

**Issue by MatteoTadiello** [acsl-mipt/multiple-sitl#6]
I'm using this tool for multiple vehicle simulation and it works fine. But QGroundControl can't connect automatically to the UAVs (stay in "Waiting for Vehicle Connection). I've tried to using a mavlink shell but can't connect to it. 

The normal build of the Firmware (make posix gazebo) automatically connect to the QGroundControl

**Comment by korotkoves** [comment]
Create new connection in QGC with ports according to README:
host 127.0.0.1
port 15010 for first instance, 15020 for second and so on

**Comment by MatteoTadiello** [comment]
Ok thanks, manually adding they I can use the uavs.
